/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AmountLock
 */
export interface AmountLock {
    /**
     * Lock identifier.
     * @type {number}
     * @memberof AmountLock
     */
    id: number;
    /**
     * Currency code.
     * @type {string}
     * @memberof AmountLock
     */
    currency: string;
    /**
     * Reserved amount.
     * @type {string}
     * @memberof AmountLock
     */
    amount: string;
    /**
     * The date and time of the lock expiration.
     * @type {string}
     * @memberof AmountLock
     */
    dateEnd: string;
    /**
     * Lock text description.
     * @type {string}
     * @memberof AmountLock
     */
    description: string;
    /**
     * An indication of whether the lock was canceled.
     * @type {boolean}
     * @memberof AmountLock
     */
    canceled: boolean;
    /**
     * Date and time of the lock cancelation.
     * @type {string}
     * @memberof AmountLock
     */
    canceledAt: string;
    /**
     * Text description on cancelation.
     * @type {string}
     * @memberof AmountLock
     */
    cancelDescription: string;
    /**
     * Date and time of the lock creation.
     * @type {Date}
     * @memberof AmountLock
     */
    createdAt: Date;
}
