/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Candle
 */
export interface Candle {
    /**
     * Candle timestamp.
     * @type {string}
     * @memberof Candle
     */
    timestamp: string;
    /**
     * Open price.
     * @type {string}
     * @memberof Candle
     */
    open: string;
    /**
     * Closing price.
     * @type {string}
     * @memberof Candle
     */
    close: string;
    /**
     * The lowest price for the period.
     * @type {string}
     * @memberof Candle
     */
    min: string;
    /**
     * The highest price for the period.
     * @type {string}
     * @memberof Candle
     */
    max: string;
}
