/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Clearing
 */
export interface Clearing {
    /**
     * Transfer timestamp in nanoseconds.
     * @type {number}
     * @memberof Clearing
     */
    timestamp: number;
    /**
     * Position identifier.
     * @type {number}
     * @memberof Clearing
     */
    positionId?: number;
    /**
     * Position quantity.
     * @type {string}
     * @memberof Clearing
     */
    positionQuantity?: string;
    /**
     * Position value in currency.
     * @type {string}
     * @memberof Clearing
     */
    positionEntryValue?: string;
    /**
     * Transfer type.
     * @type {string}
     * @memberof Clearing
     */
    type: ClearingTypeEnum;
    /**
     * Symbol code.
     * @type {string}
     * @memberof Clearing
     */
    symbol?: string;
    /**
     * Transfer currency.
     * @type {string}
     * @memberof Clearing
     */
    currency: string;
    /**
     * Transfer amount.
     * @type {string}
     * @memberof Clearing
     */
    amount: string;
    /**
     * Interest rate. It is null if the withdrawal occurred during a close trade (debt collection).
     * @type {string}
     * @memberof Clearing
     */
    rate?: string;
    /**
     * Debt value. Returned if a user was unable to pay funding during the last withdrawal but had a positive UPnL.
     * @type {string}
     * @memberof Clearing
     */
    debtDelta?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ClearingTypeEnum {
    Funding = 'funding'
}

