/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CurrencyNetworks } from './currency-networks';
/**
 * 
 * @export
 * @interface Currency
 */
export interface Currency {
    /**
     * Full currency name.
     * @type {string}
     * @memberof Currency
     */
    fullName: string;
    /**
     * Determines whether the currency belongs to a blockchain.
     * @type {boolean}
     * @memberof Currency
     */
    crypto: boolean;
    /**
     * Determines whether it is allowed to generate addresses for a deposit.
     * @type {boolean}
     * @memberof Currency
     */
    payinEnabled: boolean;
    /**
     * Determines whether the withdrawal is allowed.
     * @type {boolean}
     * @memberof Currency
     */
    payoutEnabled: boolean;
    /**
     * Determines whether the transfer between trading account and wallet account is allowed (may be disabled on maintenance).
     * @type {boolean}
     * @memberof Currency
     */
    transferEnabled: boolean;
    /**
     * Currency precision for the transfer (accepted number of digits after the decimal point).
     * @type {string}
     * @memberof Currency
     */
    precisionTransfer: string;
    /**
     * 
     * @type {Array<CurrencyNetworks>}
     * @memberof Currency
     */
    networks: Array<CurrencyNetworks>;
}
