/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CurrencyNetworks
 */
export interface CurrencyNetworks {
    /**
     * Name of the network.
     * @type {string}
     * @memberof CurrencyNetworks
     */
    network: string;
    /**
     * Token underlying standard.
     * @type {string}
     * @memberof CurrencyNetworks
     */
    protocol?: string;
    /**
     * Determines whether a network is used by default for processing currency-related transactions.
     * @type {boolean}
     * @memberof CurrencyNetworks
     */
    _default: boolean;
    /**
     * Determines whether it is allowed to generate addresses for a deposit.
     * @type {boolean}
     * @memberof CurrencyNetworks
     */
    payinEnabled: boolean;
    /**
     * Determines whether the withdrawal is allowed.
     * @type {boolean}
     * @memberof CurrencyNetworks
     */
    payoutEnabled: boolean;
    /**
     * Currency precision for the payout (accepted number of digits after the decimal point).
     * @type {string}
     * @memberof CurrencyNetworks
     */
    precisionPayout: string;
    /**
     * Default withdrawal fee.
     * @type {string}
     * @memberof CurrencyNetworks
     */
    payoutFee?: string;
    /**
     * Determines whether the providing additional information for the withdrawal is allowed.
     * @type {boolean}
     * @memberof CurrencyNetworks
     */
    payoutIsPaymentId: boolean;
    /**
     * Determines whether it is required to provide additional information other than the address for a deposit.
     * @type {boolean}
     * @memberof CurrencyNetworks
     */
    payinPaymentId: boolean;
    /**
     * Count of confirmations for the transaction.
     * @type {number}
     * @memberof CurrencyNetworks
     */
    payinConfirmations: number;
    /**
     * Regular expression for the address string.
     * @type {string}
     * @memberof CurrencyNetworks
     */
    addressRegex?: string;
    /**
     * Regular expression for the payment identifier string.
     * @type {string}
     * @memberof CurrencyNetworks
     */
    paymentIdRegex?: string;
    /**
     * The lowest processing time in seconds for the payout operation.
     * @type {string}
     * @memberof CurrencyNetworks
     */
    lowProcessingTime?: string;
    /**
     * The highest processing time in seconds for the payout operation.
     * @type {string}
     * @memberof CurrencyNetworks
     */
    highProcessingTime?: string;
    /**
     * The average processing time in seconds for the payout operation.
     * @type {string}
     * @memberof CurrencyNetworks
     */
    avgProcessingTime?: string;
}
