/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FiatToCrypto
 */
export interface FiatToCrypto {
    /**
     * Transfer identifier.
     * @type {string}
     * @memberof FiatToCrypto
     */
    id: string;
    /**
     * Provider name.
     * @type {string}
     * @memberof FiatToCrypto
     */
    providerName?: string;
    /**
     * Transaction type.
     * @type {string}
     * @memberof FiatToCrypto
     */
    orderType: string;
    /**
     * Source currency code.
     * @type {string}
     * @memberof FiatToCrypto
     */
    sourceCurrency: string;
    /**
     * Target currency code.
     * @type {string}
     * @memberof FiatToCrypto
     */
    targetCurrency: string;
    /**
     * Wallet address assigned by provider.
     * @type {string}
     * @memberof FiatToCrypto
     */
    walletAddress: string;
    /**
     * Transaction hash.
     * @type {string}
     * @memberof FiatToCrypto
     */
    txHash: string | null;
    /**
     * Amount in the target currency.
     * @type {string}
     * @memberof FiatToCrypto
     */
    targetAmount: string;
    /**
     * Amount in the source currency.
     * @type {string}
     * @memberof FiatToCrypto
     */
    sourceAmount: string;
    /**
     * Transaction status.
     * @type {string}
     * @memberof FiatToCrypto
     */
    status: FiatToCryptoStatusEnum;
    /**
     * Date and time of the transaction creation.
     * @type {Date}
     * @memberof FiatToCrypto
     */
    createdAt: Date;
    /**
     * Date and time of the last transaction update.
     * @type {Date}
     * @memberof FiatToCrypto
     */
    updatedAt: Date;
    /**
     * Date and time of the transaction deletion.
     * @type {Date}
     * @memberof FiatToCrypto
     */
    deletedAt?: Date;
    /**
     * Payment method type.
     * @type {string}
     * @memberof FiatToCrypto
     */
    paymentMethodType?: FiatToCryptoPaymentMethodTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum FiatToCryptoStatusEnum {
    INITIAL = 'INITIAL',
    INPROGRESS = 'IN_PROGRESS',
    COMPLETED = 'COMPLETED',
    FAILED = 'FAILED',
    EXPIRED = 'EXPIRED',
    UNKNOWN = 'UNKNOWN'
}
/**
    * @export
    * @enum {string}
    */
export enum FiatToCryptoPaymentMethodTypeEnum {
    CREDITCARD = 'CREDIT_CARD',
    APPLEPAY = 'APPLE_PAY',
    GOOGLEPAY = 'GOOGLE_PAY',
    SEPAMETHODTYPE = 'SEPA_METHOD_TYPE',
    GBPBANKTRANSFER = 'GBP_BANK_TRANSFER',
    SOFORTMETHODTYPE = 'SOFORT_METHOD_TYPE',
    IDEAL = 'IDEAL',
    BANKTRANSFER = 'BANK_TRANSFER',
    PROVIDER = 'PROVIDER',
    ITERAC = 'ITERAC',
    POLI = 'POLI',
    AUSTRALIAPOST = 'AUSTRALIA_POST',
    NEWSAGENT = 'NEWSAGENT',
    PAYID = 'PAYID',
    BPAY = 'BPAY'
}

