/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FundingHistory
 */
export interface FundingHistory {
    /**
     * Message timestamp.
     * @type {string}
     * @memberof FundingHistory
     */
    timestamp: string;
    /**
     * Percentage of the contract mark value paid after the end of the current funding interval.
     * @type {string}
     * @memberof FundingHistory
     */
    fundingRate: string;
    /**
     * Time-weighted average over premium indexes for *previous* funding period. Used during calculation of `funding_rate` for adjusting it to the deviation of contract market price from the mark price.
     * @type {string}
     * @memberof FundingHistory
     */
    avgPremiumIndex: string;
    /**
     * Contract interest rate for one funding period.
     * @type {string}
     * @memberof FundingHistory
     */
    interestRate: string;
    /**
     * Timestamp of the next funding.
     * @type {string}
     * @memberof FundingHistory
     */
    nextFundingTime: string;
}
