/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MarginAccount } from './margin-account';
import { MarginAccountCurrencies } from './margin-account-currencies';
import { MarginPosition } from './margin-position';
/**
 * 
 * @export
 * @interface FuturesMarginAccount
 */
export interface FuturesMarginAccount extends MarginAccount {
}


