/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SpotOrderRequest } from './spot-order-request';
/**
 * 
 * @export
 * @interface HiddenSpotOrderRequest
 */
export interface HiddenSpotOrderRequest extends SpotOrderRequest {
    /**
     * The visible part of the hidden order quantity. The only valid value is '0'.
     * @type {string}
     * @memberof HiddenSpotOrderRequest
     */
    displayQuantity?: string;
}


