/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AirdropTransactionSubtypes } from './airdrop-transaction-subtypes';
import { FuturesTransactionSubtypes } from './futures-transaction-subtypes';
import { Meta } from './meta';
import { ModelNative } from './model-native';
import { SubaccountsTransactionSubtypes } from './subaccounts-transaction-subtypes';
import { TransactionHistory } from './transaction-history';
import { TransactionSubtypes } from './transaction-subtypes';
import { TransactionTypes } from './transaction-types';
/**
 * 
 * @export
 * @interface InlineResponse20010
 */
export interface InlineResponse20010 extends TransactionHistory {
}


