/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2007
 */
export interface InlineResponse2007 {
    /**
     * Amount available for trading or transfer to wallet.
     * @type {string}
     * @memberof InlineResponse2007
     */
    available: string;
    /**
     * Total amount reserved for active orders and incomplete transfers to wallet.
     * @type {string}
     * @memberof InlineResponse2007
     */
    reserved: string;
}
