/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SubAccountBalanceFutures } from './sub-account-balance-futures';
import { SubAccountBalanceMargin } from './sub-account-balance-margin';
import { SubAccountBalanceSpot } from './sub-account-balance-spot';
/**
 * 
 * @export
 * @interface InlineResponse20013
 */
export interface InlineResponse20013 {
    /**
     * 
     * @type {SubAccountBalanceSpot & SubAccountBalanceMargin & SubAccountBalanceFutures}
     * @memberof InlineResponse20013
     */
    result?: SubAccountBalanceSpot & SubAccountBalanceMargin & SubAccountBalanceFutures;
}
