/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse20014
 */
export interface InlineResponse20014 {
    /**
     * Wallet address.
     * @type {string}
     * @memberof InlineResponse20014
     */
    address: string;
    /**
     * Payment identifier.
     * @type {string}
     * @memberof InlineResponse20014
     */
    paymentId?: string;
    /**
     * Public key.
     * @type {string}
     * @memberof InlineResponse20014
     */
    publicKey?: string;
}
