/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InternalWithdrawBody
 */
export interface InternalWithdrawBody {
    /**
     * Currency code
     * @type {string}
     * @memberof InternalWithdrawBody
     */
    currency: string;
    /**
     * The amount that will be transferred.
     * @type {string}
     * @memberof InternalWithdrawBody
     */
    amount: string;
    /**
     * Type of the beneficiary `identifier` specified below.
     * @type {string}
     * @memberof InternalWithdrawBody
     */
    by: InternalWithdrawBodyByEnum;
    /**
     * Beneficiary identifier value. Either email, username, external identifier, or phone number.
     * @type {string}
     * @memberof InternalWithdrawBody
     */
    identifier: string;
}

/**
    * @export
    * @enum {string}
    */
export enum InternalWithdrawBodyByEnum {
    Email = 'email',
    Username = 'username',
    ExternalId = 'external_id'
}

