/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IsolatedSymbolBody1
 */
export interface IsolatedSymbolBody1 {
    /**
     * Amount of currency. \"0\" to close the margin account.
     * @type {string}
     * @memberof IsolatedSymbolBody1
     */
    marginBalance: string;
    /**
     * Price and quantity will be checked for incrementation within the symbol's tick size and quantity step. See the symbol's `tick_size` and `quantity_increment`. 
     * @type {boolean}
     * @memberof IsolatedSymbolBody1
     */
    strictValidate?: boolean;
}
