/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Link
 */
export interface Link {
    /**
     * Referral link identifier.
     * @type {number}
     * @memberof Link
     */
    id: number;
    /**
     * The referral link creation timestamp.
     * @type {Date}
     * @memberof Link
     */
    createdAt: Date;
    /**
     * The referral link last update timestamp.
     * @type {Date}
     * @memberof Link
     */
    updatedAt: Date;
    /**
     * Referral link name.
     * @type {string}
     * @memberof Link
     */
    name: string;
    /**
     * Referral link hash.
     * @type {string}
     * @memberof Link
     */
    refId: string;
    /**
     * Earned balance.
     * @type {string}
     * @memberof Link
     */
    amount?: string;
    /**
     * Currency code.
     * @type {string}
     * @memberof Link
     */
    currency?: string;
    /**
     * Number of referral users for this link.
     * @type {number}
     * @memberof Link
     */
    usersCount: number;
    /**
     * An indication of whether the link was deleted.
     * @type {boolean}
     * @memberof Link
     */
    isDeleted: boolean;
}
