/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Clearing } from './clearing';
/**
 * 
 * @export
 * @interface MarginClearing
 */
export interface MarginClearing extends Clearing {
    /**
     * Trade identifier.
     * @type {number}
     * @memberof MarginClearing
     */
    tradeId?: number;
}


