/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MarginPositionHistory
 */
export interface MarginPositionHistory {
    /**
     * Position identifier.
     * @type {number}
     * @memberof MarginPositionHistory
     */
    id: number;
    /**
     * Position value in currency.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    entryValue: string;
    /**
     * Weighted average open price.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    entryPrice: string;
    /**
     * Weighted average buy price.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    avgBuyPrice: string;
    /**
     * Weighted average sell price.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    avgSellPrice: string;
    /**
     * Position quantity.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    quantity: string;
    /**
     * If the market is equal to or worse than this price a margin call will be issued.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    marginCallPrice: string;
    /**
     * The price at which the platform begins to close the position.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    liquidationPrice: string;
    /**
     * The price at which the position can no longer be closed with any non-negative PnL.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    bankruptcyPrice: string;
    /**
     * Amount of margin expressed in the quote currency.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    margin: string;
    /**
     * Margin reserved for close orders.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    requiredMargin: string;
    /**
     * Margin reserved for open orders.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    ordersMargin: string;
    /**
     * Unrealized Profit and Loss.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    pnl: string;
    /**
     * Position leverage.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    leverage: string;
    /**
     * Mode of margin trading.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    marginMode: MarginPositionHistoryMarginModeEnum;
    /**
     * Position state.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    state: MarginPositionHistoryStateEnum;
    /**
     * Symbol code.
     * @type {string}
     * @memberof MarginPositionHistory
     */
    symbol: string;
    /**
     * Flag indicating the position is close to the liquidation, and increased margin may prevent it from happening.
     * @type {boolean}
     * @memberof MarginPositionHistory
     */
    marginCall: boolean;
    /**
     * Timestamp of the position creation in nanoseconds.
     * @type {number}
     * @memberof MarginPositionHistory
     */
    createTimestamp: number;
    /**
     * Timestamp of the position last update in nanoseconds.
     * @type {number}
     * @memberof MarginPositionHistory
     */
    updateTimestamp: number;
}

/**
    * @export
    * @enum {string}
    */
export enum MarginPositionHistoryMarginModeEnum {
    Isolated = 'isolated'
}
/**
    * @export
    * @enum {string}
    */
export enum MarginPositionHistoryStateEnum {
    Closed = 'closed',
    Active = 'active',
    Liquidated = 'liquidated'
}

