/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HiddenMarginOrderRequest } from './hidden-margin-order-request';
import { MarginOrderRequest } from './margin-order-request';
/**
 * 
 * @export
 * @interface MarginOrderBody
 */
export interface MarginOrderBody extends HiddenMarginOrderRequest {
    /**
     * Reduce-only order, being filled, guarantees not to put the position quantity to the point when the position flips.
     * @type {boolean}
     * @memberof MarginOrderBody
     */
    reduceOnly?: boolean;
}
