/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FiatToCrypto } from './fiat-to-crypto';
import { InstantExchange } from './instant-exchange';
/**
 * 
 * @export
 * @interface Meta
 */
export interface Meta {
    /**
     * 
     * @type {FiatToCrypto}
     * @memberof Meta
     */
    fiatToCrypto?: FiatToCrypto;
    /**
     * 
     * @type {InstantExchange}
     * @memberof Meta
     */
    instantExchange?: InstantExchange;
}
