/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OperationDeposit
 */
export interface OperationDeposit {
    /**
     * Transaction bank identifier.
     * @type {string}
     * @memberof OperationDeposit
     */
    requestId: string;
    /**
     * Transaction status:   * *CREATED* — the transaction has been created and needs to be approved. It remains in this status until manually validated or moved to a blockchain.   * *PENDING* — the transaction has been created and is queued until the fees are paid and it can be processed further. Blockchain confirmations have not yet been gathered.   * *FAILED* — the transaction could not be committed.   * *SUCCESS* — the transaction has been approved and fully processed.   * *ROLLED_BACK* — the transaction has been canceled. 
     * @type {string}
     * @memberof OperationDeposit
     */
    status: OperationDepositStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum OperationDepositStatusEnum {
    CREATED = 'CREATED',
    PENDING = 'PENDING',
    SUCCESS = 'SUCCESS',
    ROLLEDBACK = 'ROLLED_BACK',
    FAILED = 'FAILED'
}

