/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OrderClientOrderIdBody1
 */
export interface OrderClientOrderIdBody1 {
    /**
     * Order quantity.
     * @type {string}
     * @memberof OrderClientOrderIdBody1
     */
    quantity: string;
    /**
     * Order price. Required if `type` is `limit`, `stopLimit`, or `takeProfitLimit`.
     * @type {string}
     * @memberof OrderClientOrderIdBody1
     */
    price: string;
    /**
     * Unique order identifier for a new order.
     * @type {string}
     * @memberof OrderClientOrderIdBody1
     */
    newClientOrderId?: string;
    /**
     * Price and quantity will be checked for incrementation within the symbol's tick size and quantity step. See the symbol's `tick_size` and `quantity_increment`. 
     * @type {boolean}
     * @memberof OrderClientOrderIdBody1
     */
    strictValidate?: boolean;
}
