/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OrderClientOrderIdBody2
 */
export interface OrderClientOrderIdBody2 {
    /**
     * Order quantity.
     * @type {string}
     * @memberof OrderClientOrderIdBody2
     */
    quantity: string;
    /**
     * Order price. Required if `type` is `limit`, `stopLimit`, or `takeProfitLimit`.
     * @type {string}
     * @memberof OrderClientOrderIdBody2
     */
    price?: string;
    /**
     * Client order identifier for a new order.
     * @type {string}
     * @memberof OrderClientOrderIdBody2
     */
    newClientOrderId: string;
}
