/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FuturesOrderRequest } from './futures-order-request';
import { HiddenFuturesOrderRequest } from './hidden-futures-order-request';
/**
 * 
 * @export
 * @interface OrderListBody5
 */
export interface OrderListBody5 {
    /**
     * Order list identifier.
     * @type {string}
     * @memberof OrderListBody5
     */
    orderListId?: string;
    /**
     * Order list type.
     * @type {string}
     * @memberof OrderListBody5
     */
    contingencyType: OrderListBody5ContingencyTypeEnum;
    /**
     * 
     * @type {Array<HiddenFuturesOrderRequest & FuturesOrderRequest>}
     * @memberof OrderListBody5
     */
    orders: Array<HiddenFuturesOrderRequest & FuturesOrderRequest>;
}

/**
    * @export
    * @enum {string}
    */
export enum OrderListBody5ContingencyTypeEnum {
    OneCancelOther = 'oneCancelOther',
    OneTriggerOther = 'oneTriggerOther',
    OneTriggerOneCancelOther = 'oneTriggerOneCancelOther'
}

