/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PriceHistoryHistory } from './price-history-history';
/**
 * 
 * @export
 * @interface PriceHistory
 */
export interface PriceHistory {
    /**
     * Quote currency code.
     * @type {string}
     * @memberof PriceHistory
     */
    currency: string;
    /**
     * 
     * @type {PriceHistoryHistory}
     * @memberof PriceHistory
     */
    history: PriceHistoryHistory;
}
