/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Price
 */
export interface Price {
    /**
     * Quote currency code.
     * @type {string}
     * @memberof Price
     */
    currency: string;
    /**
     * Quotation price.
     * @type {string}
     * @memberof Price
     */
    price: string;
    /**
     * Last update or refresh price timestamp.
     * @type {string}
     * @memberof Price
     */
    timestamp: string;
}
