/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PublicTrade
 */
export interface PublicTrade {
    /**
     * Trade identifier.
     * @type {number}
     * @memberof PublicTrade
     */
    id: number;
    /**
     * Trade price.
     * @type {string}
     * @memberof PublicTrade
     */
    price: string;
    /**
     * Trade quantity.
     * @type {string}
     * @memberof PublicTrade
     */
    qty: string;
    /**
     * Trade side.
     * @type {string}
     * @memberof PublicTrade
     */
    side: PublicTradeSideEnum;
    /**
     * Trade timestamp.
     * @type {string}
     * @memberof PublicTrade
     */
    timestamp: string;
}

/**
    * @export
    * @enum {string}
    */
export enum PublicTradeSideEnum {
    Sell = 'sell',
    Buy = 'buy'
}

