/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SpotOrderTrades
 */
export interface SpotOrderTrades {
    /**
     * Trade identifier.
     * @type {number}
     * @memberof SpotOrderTrades
     */
    id: number;
    /**
     * Quantity of trade.
     * @type {string}
     * @memberof SpotOrderTrades
     */
    quantity: string;
    /**
     * Trade price.
     * @type {string}
     * @memberof SpotOrderTrades
     */
    price: string;
    /**
     * Fee paid for trade.
     * @type {string}
     * @memberof SpotOrderTrades
     */
    fee: string;
    /**
     * Date of trade.
     * @type {string}
     * @memberof SpotOrderTrades
     */
    timestamp: string;
    /**
     * Liquidity indicator.
     * @type {boolean}
     * @memberof SpotOrderTrades
     */
    taker: boolean;
}
