/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Wallet } from './wallet';
import { WalletBalance } from './wallet-balance';
/**
 * 
 * @export
 * @interface SubAccountBalanceMargin
 */
export interface SubAccountBalanceMargin {
    /**
     * 
     * @type {Wallet}
     * @memberof SubAccountBalanceMargin
     */
    wallet: Wallet;
    /**
     * 
     * @type {Array<WalletBalance & any>}
     * @memberof SubAccountBalanceMargin
     */
    spot: Array<WalletBalance & any>;
}
