/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SubAccount
 */
export interface SubAccount {
    /**
     * User identifier.
     * @type {number}
     * @memberof SubAccount
     */
    subAccountId: number;
    /**
     * User's email address.
     * @type {string}
     * @memberof SubAccount
     */
    email: string;
    /**
     * User account status:   * *new* — account is created, but not confirmed by email.   * *active* — account is fully functioning (it is normally accomplished after email confirmation).   * *disable* — account is disabled (the user cannot initiate account deactivation — it can only be done by the CRM operator). 
     * @type {string}
     * @memberof SubAccount
     */
    status: SubAccountStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SubAccountStatusEnum {
    New = 'new',
    Active = 'active',
    Disable = 'disable'
}

