/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SubaccountTransferBody
 */
export interface SubaccountTransferBody {
    /**
     * Sub-account identifier.
     * @type {number}
     * @memberof SubaccountTransferBody
     */
    subAccountId: number;
    /**
     * Amount of funds to transfer.
     * @type {string}
     * @memberof SubaccountTransferBody
     */
    amount: string;
    /**
     * Currency code.
     * @type {string}
     * @memberof SubaccountTransferBody
     */
    currency: string;
    /**
     * Transfer type.
     * @type {string}
     * @memberof SubaccountTransferBody
     */
    type: SubaccountTransferBodyTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SubaccountTransferBodyTypeEnum {
    ToSubAccount = 'to_sub_account',
    FromSubAccount = 'from_sub_account'
}

