/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SubaccountAclBody
 */
export interface SubaccountAclBody {
    /**
     * A comma-separated list of sub-accounts.
     * @type {Array<string>}
     * @memberof SubaccountAclBody
     */
    subAccountIds: Array<string>;
    /**
     * Value indicating the desired state of deposits.
     * @type {boolean}
     * @memberof SubaccountAclBody
     */
    depositAddressGenerationEnabled: boolean;
    /**
     * Value indicating the desired state of withdrawals.
     * @type {boolean}
     * @memberof SubaccountAclBody
     */
    withdrawEnabled: boolean;
    /**
     * Text description for the ACL setting.
     * @type {string}
     * @memberof SubaccountAclBody
     */
    description?: string;
}
