/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Ticker
 */
export interface Ticker {
    /**
     * Best ask price.
     * @type {string}
     * @memberof Ticker
     */
    ask: string | null;
    /**
     * Best bid price.
     * @type {string}
     * @memberof Ticker
     */
    bid: string | null;
    /**
     * Last trade price.
     * @type {string}
     * @memberof Ticker
     */
    last: string | null;
    /**
     * The lowest trade price within 24 hours.
     * @type {string}
     * @memberof Ticker
     */
    low: string;
    /**
     * The highest trade price within 24 hours.
     * @type {string}
     * @memberof Ticker
     */
    high: string;
    /**
     * Last trade price 24 hours ago.
     * @type {string}
     * @memberof Ticker
     */
    open: string | null;
    /**
     * Total trading amount within 24 hours in base currency.
     * @type {string}
     * @memberof Ticker
     */
    volume: string;
    /**
     * Total trading amount within 24 hours in quote currency.
     * @type {string}
     * @memberof Ticker
     */
    volumeQuote: string;
    /**
     * Last update or refresh ticker timestamp.
     * @type {string}
     * @memberof Ticker
     */
    timestamp: string;
}
