/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TickerPrice
 */
export interface TickerPrice {
    /**
     * Ticker last price.
     * @type {string}
     * @memberof TickerPrice
     */
    price: string | null;
    /**
     * Last update or refresh ticker timestamp.
     * @type {string}
     * @memberof TickerPrice
     */
    timestamp: string;
}
