/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TradingFee
 */
export interface TradingFee {
    /**
     * Symbol code.
     * @type {string}
     * @memberof TradingFee
     */
    symbol?: string;
    /**
     * Liquidity taker fee, a fraction of order volume such as 0.001 (for 0.1% fee).
     * @type {string}
     * @memberof TradingFee
     */
    takeRate: string;
    /**
     * Liquidity provider fee, a fraction of order volume such as 0.001 (for 0.1% fee).
     * @type {string}
     * @memberof TradingFee
     */
    makeRate: string;
}
