/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TransactionLimit
 */
export interface TransactionLimit {
    /**
     * Currency code of limits (fiat).
     * @type {string}
     * @memberof TransactionLimit
     */
    currencyCode: string;
    /**
     * Target currency minimum amount.
     * @type {string}
     * @memberof TransactionLimit
     */
    min: string;
    /**
     * Target currency maximum amount.
     * @type {string}
     * @memberof TransactionLimit
     */
    max: string;
    /**
     * Source currency code.
     * @type {string}
     * @memberof TransactionLimit
     */
    sourceCode: string;
    /**
     * Target currency code.
     * @type {string}
     * @memberof TransactionLimit
     */
    targetCode: string;
    /**
     * Source currency minimum amount.
     * @type {string}
     * @memberof TransactionLimit
     */
    sourceMin: string;
    /**
     * Source currency maximum amount.
     * @type {string}
     * @memberof TransactionLimit
     */
    sourceMax: string;
}
