/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TransactionFeeFees
 */
export interface TransactionFeeFees {
    /**
     * Fee name.
     * @type {string}
     * @memberof TransactionFeeFees
     */
    name?: string;
    /**
     * Fee amount.
     * @type {number}
     * @memberof TransactionFeeFees
     */
    amount?: number;
    /**
     * Fee type.
     * @type {string}
     * @memberof TransactionFeeFees
     */
    type?: string;
}
