/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Transfer
 */
export interface Transfer {
    /**
     * Payment identifier.
     * @type {number}
     * @memberof Transfer
     */
    id: number;
    /**
     * Transaction bank identifier.
     * @type {string}
     * @memberof Transfer
     */
    txId: string;
    /**
     * Provider identifier.
     * @type {number}
     * @memberof Transfer
     */
    providerId: number;
    /**
     * Currency code.
     * @type {string}
     * @memberof Transfer
     */
    currency: string;
    /**
     * Amount of funds.
     * @type {string}
     * @memberof Transfer
     */
    amount: string;
    /**
     * Main account balance.
     * @type {string}
     * @memberof Transfer
     */
    balance: string;
}
