/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @enum {string}
 */
export enum TransactionSubtypes {
    UNCLASSIFIED = 'UNCLASSIFIED',
    BLOCKCHAIN = 'BLOCKCHAIN',
    AFFILIATE = 'AFFILIATE',
    OFFCHAIN = 'OFFCHAIN',
    FIAT = 'FIAT',
    WALLETTOSPOT = 'WALLET_TO_SPOT',
    SPOTTOWALLET = 'SPOT_TO_WALLET',
    CHAINSWITCHFROM = 'CHAIN_SWITCH_FROM',
    CHAINSWITCHTO = 'CHAIN_SWITCH_TO'
}

