/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WalletConvertBody
 */
export interface WalletConvertBody {
    /**
     * Source currency code.
     * @type {string}
     * @memberof WalletConvertBody
     */
    fromCurrency: string;
    /**
     * Target currency code.
     * @type {string}
     * @memberof WalletConvertBody
     */
    toCurrency: string;
    /**
     * The amount that will be sent to the specified address.
     * @type {string}
     * @memberof WalletConvertBody
     */
    amount: string;
}
