/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WithdrawRequest
 */
export interface WithdrawRequest {
    /**
     * Currency code.
     * @type {string}
     * @memberof WithdrawRequest
     */
    currency: string;
    /**
     * The amount that will be sent to the specified address.
     * @type {string}
     * @memberof WithdrawRequest
     */
    amount: string;
    /**
     * Address identifier.
     * @type {string}
     * @memberof WithdrawRequest
     */
    address: string;
    /**
     * An additional identifier required for specific currencies (for example, \"Memo\").
     * @type {string}
     * @memberof WithdrawRequest
     */
    paymentId?: string;
    /**
     * If 'true', the sender is willing to include fee expenses to the amount of operation, so the beneficiary will receive the sum reduced by fees.
     * @type {boolean}
     * @memberof WithdrawRequest
     */
    includeFee?: boolean | null;
    /**
     * If 'false', then the sender should commit or rollback a transaction in an hour. After 1 hour, the transaction will automatically be rolled back.
     * @type {boolean}
     * @memberof WithdrawRequest
     */
    autoCommit?: boolean | null;
    /**
     * Whether the withdrawal may be committed offchain. If 'required' is selected, then only offchain transaction can be created. 
     * @type {string}
     * @memberof WithdrawRequest
     */
    useOffchain?: WithdrawRequestUseOffchainEnum;
    /**
     * Text comment to transaction.
     * @type {string}
     * @memberof WithdrawRequest
     */
    publicComment?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum WithdrawRequestUseOffchainEnum {
    Never = 'never',
    Optionally = 'optionally',
    Required = 'required'
}

