/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Create API keys in your profile and use public API key as username and secret API key as password to authorize.
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Transfer } from './transfer';
/**
 * 
 * @export
 * @interface Withdrawal
 */
export interface Withdrawal extends Transfer {
    /**
     * Method identifier.
     * @type {string}
     * @memberof Withdrawal
     */
    methodId: string;
    /**
     * Method type:   * *ACH* — automated Clearing House, transfer between bank accounts in the US.   * *CREDIT_CARD* — transfer using a bank card.   * *UNKNOWN* — all other method types. 
     * @type {string}
     * @memberof Withdrawal
     */
    methodType: WithdrawalMethodTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum WithdrawalMethodTypeEnum {
    ACH = 'ACH',
    CREDITCARD = 'CREDIT_CARD',
    UNKNOWN = 'UNKNOWN'
}

